upstreamProjects:
  Mule-runtime/metadata-model-api/master-JULY-2022-DRY-RUN,
  Mule-runtime/mule-artifact-declaration/master-JULY-2022-DRY-RUN
# Comment public setting to get oldMuleArtifact 4.3.0 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
